### ISSUE TITLE
Dependencies version issue.

### ISSUE THREAD

**Issue by VictorJava** [fooock/phone-tracker#5]
Hi thanks for the library. 

following your suggestions 
repositories {
    jcenter()
}

And in your dependencies block add this line

compile 'com.fooock:phone-tracker:0.2.0'

but it couldn`t be found. Because the version of jar wasn`t been specifyend. Please see 
https://bintray.com/fooock/maven/phone-tracker/0.2.0#files/com%2Ffooock%2Fphone-tracker%2Funspecified

Temporary small hack 
  implementation 'com.fooock:phone-tracker:unspecified'

**Comment by fooock** [comment]
Thanks for the report!. I fixed this issue and submitted a new version (`0.2.1`)

**Comment by fooock** [comment]
Closed
